### ISSUE TITLE
Setup relative url

### ISSUE THREAD

**Issue by stilobique** [peterdesmet/pelican-cover-image#2]
Hello,
I use this plugin, it works very well, but if the site is in WIP, I mean, works locally and nothing is pushed remotely, no way to use a local image, the template uses an absolute URL, my settings with pelican are yet configured with `RELATIVE_URLS = True`.

**Comment by peterdesmet** [comment]
👋 Good to hear you find this plugin useful. I don't use Pelican (and thus this plugin) anymore, so I'm no longer actively maintaining this plugin. If you are welcome to submit a pull request though.

**Comment by peterdesmet** [comment]
Fixed in #4
